### ISSUE TITLE
npm start not working on Ubuntu 17.10

### ISSUE THREAD

**Issue by joshas** [ionic-team/ionic-pwa-toolkit#9] opened 2018-01-25 19:23 UTC
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/starter@0.0.1
@stencil/core@0.2.1
```

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
Running `npm start` completes build with "build finished, watching for changes..." message, but app is never loaded in browser, stuck with "Initializing First Build" message. After few moments disk read or write (not really sure which) usage ramps up and OS freezes.

**Expected behavior:**
App is built and displayed in browser.

**Steps to reproduce:**
Ununtu 17.10 64-bit, nodejs v8.9.4, npm v5.6.0
Use 'Getting started' section from README.md, run `npm start`.

**Comment by jgw96** [comment] 2018-01-29 19:25
Hey! Thanks for opening an issue with us. Does the same happen with https://github.com/ionic-team/stencil-app-starter ?

**Comment by joshas** [comment] 2018-01-29 19:41
No, stencil-app-starter works as correctly.

**Comment by jgw96** [comment] 2018-01-30 20:40
Hmm, I cannot reproduce this in ubuntu for windows 10. Do you have a machine running windows or a mac that you can test this with? Interested to see if it's just your ubuntu machine that is having the problem.

**Comment by joshas** [comment] 2018-01-30 20:45
On Windows 7 ionic-pwa-toolkit works just fine. I might try running pwa-toolkit on clean installation or just LiveISO.

**Comment by kael** [comment] 2018-02-03 08:59
@joshas I had a similar issue, with _"Initializing First Build"_ displayed in the browser.

I deleted the directory, re-cloned the repo and now it's up, although I get this in the console:

```shell
$ npm start

> @stencil/starter@0.0.1 start /home/kael/dev/projects/pwa
> npm run dev


> @stencil/starter@0.0.1 dev /home/kael/dev/projects/pwa
> sd concurrent "stencil build --dev --watch" "stencil-dev-server" 

Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/kael/dev/projects/pwa/node_modules/opn/index.js:84:13)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
[51:09.6]  @stencil/core v0.2.1 
[51:09.6]  build, app, dev mode, started ... 
[51:09.7]  compile started ... 
[51:26.7]  compile finished in 17.07 s 
[51:48.4]  generate bundles started ... 
[51:48.5]  generate bundles finished in 19 ms 
[51:48.5]  generate app files started ... 
[51:54.8]  compile global style start ... 
[51:54.8]  compile global style finish in 3 ms 
[51:54.8]  generate app files finished in 6.33 s 
[51:55.9]  build finished, watching for changes... in 46.30 s 
```

OS: Ubuntu 16.04.3 LTS
Node: v6.12.2
NPM: 3.10.10

**Comment by joshas** [comment] 2018-02-03 10:15
@kael Could you try upgrading node to v8? That might fix errors in console, but you'll probably be stuck with my original issue.

**Comment by kael** [comment] 2018-02-03 11:32
Well, APT only proposed an update to _Node v6.12.3_. I'd rather not install another version for now (unless it might be necessary ?)

**Comment by kael** [comment] 2018-02-05 17:42
FYI, I've updated to _Node v8.9.4_ but I still get that error (without apparent buggy effect):
```bash
Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/kael/dev/projects/pwa/node_modules/opn/index.js:82:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

**Comment by jgw96** [comment] 2018-02-19 17:41
Hello all! Is this only happening on linux?

**Comment by joshas** [comment] 2018-02-19 17:52
@jgw96 Yes, my reported issue was encountered on Linux.

**Comment by AnthoniG** [comment] 2018-03-22 10:52
Just wanted to add that I ran this on Linux Mint 18 Sylvia and it ran fine. It really, really does like starting with Yarn which is a great shame. Other than that it worked fine.

As a side note: How do I stop it from opening a browser by default? In create-react-app I can add a .env file and then include BROWSER=None however it doesn't seem to work for this.

**Comment by jgw96** [comment] 2018-04-17 14:54
Hello all! @joshas since this seems to be isolated to your linux machine I am going to have to close this issue for now. @AnthoniG you can pass the --no-open option in your dev command like this ```     "dev": "sd concurrent \"stencil build --dev --watch\" \"stencil-dev-server\ --no-open" "```. Thanks!

**Closed by jgw96** 2018-04-17 14:54 UTC
Labels: needs reply
