### ISSUE TITLE
@ionic/core/... Type 'keyof B' does not satisfy the constraint 'string'. Type 'string | number | symbol' is not assignable to type 'string'. Type 'number' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-pwa-toolkit#70] opened 2018-06-17 05:26 UTC
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):
```
@stencil/core v0.9.7
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Build fail

![capture321](https://user-images.githubusercontent.com/140737/41504995-8cb78d56-71b3-11e8-9091-1088f809d4d8.png)

**Expected behavior:**
Starter works

**Steps to reproduce:**

**Other information:**
```
C:\ae\adaept.com\aepwa>ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.
cli packages: (C:\Users\peter\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

System:

   NodeJS : v8.11.1
   npm    : 6.1.0-next.0
   OS     : Windows 10

C:\ae\adaept.com\aepwa>
```

I ran `npm audit fix` and it reported corrected 4 security errors.

Repo:
https://github.com/peterennis/aepwa

**Comment by adamlacombe** [comment] 2018-06-21 22:41
Duplicate of #68 

Fix: [@ionic/core#15dc651](https://github.com/ionic-team/ionic/commit/15dc651494feed7f2f77d0b76f2482fa1626e981#diff-24fcc947660e79d1b2f094ec1b7dc3f5)

**Comment by peterennis** [comment] 2018-06-22 00:47
Not fixed in @ionic/core@4.0.0-alpha.7 - maybe in the next release.

![capture015](https://user-images.githubusercontent.com/140737/41752246-1702c65e-757b-11e8-920a-48972fa7f25d.png)

**Comment by pedrotcm** [comment] 2018-07-03 13:09
Not fixed in @ionic/core@4.0.0-alpha.7.

**Comment by pedrotcm** [comment] 2018-07-03 13:09
Not fixed in @ionic/core@4.0.0-alpha.7.

**Comment by adamlacombe** [comment] 2018-07-03 15:35
Yes - the upcoming release has the [fix](https://github.com/ionic-team/ionic/commit/15dc651494feed7f2f77d0b76f2482fa1626e981#diff-24fcc947660e79d1b2f094ec1b7dc3f5). For the time being you can replace `<keyof B>` with `<any>` in node_modules/@ionic/core/dist/types/utils/overlays.d.ts

**Comment by adamdbradley** [comment] 2018-07-14 22:02
This is fixed as of alpha.10. Thanks

**Closed by adamdbradley** 2018-07-14 22:02 UTC
Labels: triage
